# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Entropy_config = debug
  UnitTests_config = debug
  Trespass_config = debug

else ifeq ($(config),release)
  Entropy_config = release
  UnitTests_config = release
  Trespass_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Entropy UnitTests Trespass

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Entropy:
ifneq (,$(Entropy_config))
	@echo "==== Building Entropy ($(Entropy_config)) ===="
	@${MAKE} --no-print-directory -C . -f Entropy.make config=$(Entropy_config)
endif

UnitTests: Entropy
ifneq (,$(UnitTests_config))
	@echo "==== Building UnitTests ($(UnitTests_config)) ===="
	@${MAKE} --no-print-directory -C . -f UnitTests.make config=$(UnitTests_config)
endif

Trespass: Entropy
ifneq (,$(Trespass_config))
	@echo "==== Building Trespass ($(Trespass_config)) ===="
	@${MAKE} --no-print-directory -C . -f Trespass.make config=$(Trespass_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Entropy.make clean
	@${MAKE} --no-print-directory -C . -f UnitTests.make clean
	@${MAKE} --no-print-directory -C . -f Trespass.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Entropy"
	@echo "   UnitTests"
	@echo "   Trespass"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"